spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    # Change the colon to a slash here
    url: jdbc:oracle:thin:@localhost:1521/freepdb1  # <-- THIS IS THE FIX
    username: scott
    password: tiger

  jpa:
    hibernate:
<<<<<<< HEAD
      ddl-auto: validate
=======
      ddl-auto: update
>>>>>>> 08363241cb8fd388720ec4e6b16b7d5e0c05c6fe
    # To be extra safe, explicitly tell Hibernate which SQL dialect to use
    database-platform: org.hibernate.dialect.OracleDialect # <-- ADD THIS LINE
    show-sql: true
    properties:
      hibernate:
        format_sql: true